[package]
name = "scattered-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
prost = "0.14.1"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.14.2"
tonic-prost = "0.14.2"

[build-dependencies]
prost-build = "0.14.1"
tonic-prost-build = "0.14.2"
